FROM ubuntu:18.04

RUN apt-get update \
    && apt-get clean \ 
    && apt-get install rsyslog vim -y \
    && service rsyslog start \
    && echo '# Enable UDP syslog receiver\nmodule(load="imudp")\ninput(type="imudp" port="514")' >> /etc/rsyslog.conf


COPY syslog_always_alive.sh /tmp/syslog_always_alive.sh
COPY rsyslog_haproxy.conf /etc/rsyslog.d/haproxy.conf

RUN chmod +x /tmp/syslog_always_alive.sh

EXPOSE 514/udp
CMD ["/tmp/syslog_always_alive.sh"] 
